#!/usr/bin/env python3
"""Emit what the extraction agents did, for the site to render.

The corpus is produced by language models end to end and checked by no human. A site that
says so in a sentence and shows nothing is asking to be taken on trust. This emits the actual
record: which agent role read which part of the paper, under which prompt, using which model,
what each proposed, the verbatim sentence it based each claim on, and where the agents
disagreed.

Only one paper has this record. The other nine were extracted before agent runs were saved,
so `runs/` holds a full trace for Gaedeke alone. The generated data says which papers have a
trace so the pages can state that rather than render empty templates.

Reads what the layers produce — `runs/<paper>/reconciler.output.json` and the three
`<reader>.output.json` beside it — because that is what the repository contains. It used to
read `extract/out/`, which is not in the repository at all: the data behind the agents page
was committed once and could not be regenerated by the script that claims to generate it.

Writes `site/src/data/agents.json`:

  roles       the seven roles, each with its prompt text read from extract/prompts/
  papers      per paper: per-agent counts, the model used, and every drafted claim with the
              agents that proposed it and the evidence each quoted
  agreement   how many claims more than one reader found

Usage:
  python3 scripts/agents_report.py
  python3 scripts/agents_report.py --print
"""

from __future__ import annotations

import argparse
import json
import os
from collections import Counter

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROMPTS = os.path.join(ROOT, "extract", "prompts")
RUNS = os.path.join(ROOT, "runs")
OUT = os.path.join(ROOT, "site", "src", "data", "agents.json")

# The pipeline in order. `stage` groups them: three readers work in parallel on different
# slices of the paper, then the rest run in sequence over their output.
ROLES = [
    {"id": "results-reader", "stage": "read", "reads": "the Results section",
     "returns": "candidate claims, each with a panel, a role and the sentence it rests on",
     "agent_key": "results"},
    {"id": "caption-reader", "stage": "read", "reads": "figure and table captions",
     "returns": "candidate claims anchored to the panel they describe",
     "agent_key": "caption"},
    {"id": "structure-reader", "stage": "read", "reads": "the abstract and section structure",
     "returns": "candidate claims the paper frames as its own conclusions",
     "agent_key": "structure"},
    {"id": "reconciler", "stage": "reconcile",
     "reads": "all three readers' output",
     "returns": "one draft table, each claim tagged by how many readers proposed it",
     "agent_key": None},
    {"id": "external-reviewer", "stage": "reconcile",
     "reads": "the draft table and the paper",
     "returns": "a revised table — this is what stands in for a human review step",
     "agent_key": None},
    {"id": "edge-inference", "stage": "relate", "reads": "the reconciled claims",
     "returns": "typed relations between them — the deductive spine",
     "agent_key": None},
    {"id": "coverage-adjudicator", "stage": "cover",
     "reads": "unmatched spans of the paper and the claim tree",
     "returns": "a covered / gap / no-assertion verdict for each span",
     "agent_key": None},
    {"id": "questions", "stage": "relate",
     "reads": "the abstract and the paper's hypothesis and alt- claims",
     "returns": "the research questions the paper states, and which claim answers each",
     "agent_key": None},
    {"id": "parts", "stage": "relate",
     "reads": "the tree's claims, with their roles, panels and edges",
     "returns": "the `part-of` edges — which claims are components of other claims",
     "agent_key": None},
    {"id": "stance", "stage": "relate",
     "reads": "the tree's controls and empirical claims, the questions, and the Results prose",
     "returns": "the alternatives the paper rejects, and the `rules-out` edges from its controls",
     "agent_key": None},
    {"id": "summaries", "stage": "measure",
     "reads": "the claim graph — every claim's role, sentence and edges",
     "returns": "the paper in three paragraphs: hypotheses, claims and inferences",
     "agent_key": None},
    {"id": "synthesis", "stage": "measure",
     "reads": "the claim graph alone — no abstract, no prose",
     "returns": "the argument restated from the graph, traced back to the claims and edges",
     "agent_key": None},
    {"id": "abstract-map", "stage": "measure",
     "reads": "the abstract cut into sentences and the claim list",
     "returns": "which claims each abstract sentence carries, and which claims it drops",
     "agent_key": None},
]


def prompt_text(role_id):
    p = os.path.join(PROMPTS, f"{role_id}.md")
    if not os.path.isfile(p):
        return None
    with open(p, encoding="utf-8") as fh:
        return fh.read()


# A role is sent its task file and the contract files its layer declares. The declaration is
# the source here rather than a second copy of the map in extract/elife_extract/prompts.py:
# a test holds the two equal, and this script stays standard-library-plus-PyYAML.
LAYER_OF = {"results-reader": "results-reader", "caption-reader": "caption-reader",
            "structure-reader": "structure-reader", "reconciler": "reconcile",
            "external-reviewer": "external-review", "edge-inference": "edge-inference",
            "coverage-adjudicator": "adjudication", "questions": "questions",
            "parts": "parts", "stance": "stance", "summaries": "summaries",
            "synthesis": "synthesis", "abstract-map": "abstract-map"}


def declared_reads():
    import yaml
    with open(os.path.join(ROOT, "pipeline", "layers.yaml"), encoding="utf-8") as fh:
        decl = yaml.safe_load(fh)
    return {l["id"]: l.get("reads") or [] for l in decl["layers"]}


def contract_files():
    d = os.path.join(PROMPTS, "contract")
    out = []
    for name in sorted(os.listdir(d)) if os.path.isdir(d) else []:
        with open(os.path.join(d, name), encoding="utf-8") as fh:
            text = fh.read()
        out.append({"path": f"extract/prompts/contract/{name}", "text": text,
                    "lines": len(text.splitlines())})
    return out


# The reconcile layer's output is the draft; each reader's output names the model that
# answered it. Both are what `pipeline.py run` records the hashes of.
READERS = {"results": "results-reader", "caption": "caption-reader",
           "structure": "structure-reader"}


def paper_trace(slug):
    draft_p = os.path.join(RUNS, slug, "reconciler.output.json")
    if not os.path.isfile(draft_p):
        return None
    with open(draft_p, encoding="utf-8") as fh:
        draft = json.load(fh)

    models = {}
    for key, layer_id in READERS.items():
        p = os.path.join(RUNS, slug, f"{layer_id}.output.json")
        if os.path.isfile(p):
            with open(p, encoding="utf-8") as fh:
                models[key] = json.load(fh).get("model")

    claims = []
    for c in draft.get("claims", []):
        claims.append({
            "claim": c.get("claim"),
            "panel": c.get("panel"),
            "role": c.get("role"),
            "confidence": c.get("confidence"),
            "sources": sorted(c.get("sources") or []),
            "evidence_by_agent": c.get("evidence_by_agent") or {},
        })

    by_n = Counter(len(c["sources"]) for c in claims)
    return {
        "paper_slug": slug,
        "paper_title": draft.get("paper_title"),
        "paper_doi": draft.get("paper_doi"),
        "extraction_path": draft.get("extraction_path"),
        "per_agent_counts": draft.get("per_agent_counts") or {},
        "models": models,
        "config": draft.get("config_snapshot") or {},
        "claims": claims,
        "drafted": len(claims),
        "found_by_one": by_n.get(1, 0),
        "found_by_more": sum(v for n, v in by_n.items() if n > 1),
    }


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--print", dest="show", action="store_true")
    a = ap.parse_args()

    reads = declared_reads()
    roles = []
    for r in ROLES:
        text = prompt_text(r["id"])
        roles.append({**r, "prompt": text,
                      "prompt_lines": len(text.splitlines()) if text else 0,
                      "prompt_path": f"extract/prompts/{r['id']}.md" if text else None,
                      "contract_paths": [p for p in reads.get(LAYER_OF.get(r["id"], ""), [])
                                         if "/contract/" in p]})

    slugs = sorted(d for d in os.listdir(RUNS)
                   if os.path.isfile(os.path.join(RUNS, d, "reconciler.output.json"))) \
        if os.path.isdir(RUNS) else []
    papers = {s: paper_trace(s) for s in slugs}
    papers = {k: v for k, v in papers.items() if v}

    data = {"roles": roles, "contract": contract_files(), "papers": papers,
            "papers_with_trace": sorted(papers)}

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as fh:
        json.dump(data, fh, indent=2, sort_keys=True)
        fh.write("\n")

    missing = [r["id"] for r in roles if not r["prompt"]]
    print(f"agents → {os.path.relpath(OUT, ROOT)}")
    print(f"  {len(roles)} roles, {len(roles) - len(missing)} with a committed prompt"
          + (f" — missing: {', '.join(missing)}" if missing else ""))
    for s, p in papers.items():
        print(f"  {s}: {p['drafted']} drafted claims · "
              f"{p['found_by_more']} found by more than one reader · "
              f"{', '.join(f'{k} {v}' for k, v in p['per_agent_counts'].items())}")
    if not papers:
        print("  no paper has a saved agent trace")
    if a.show:
        print(json.dumps({k: v for k, v in data.items() if k != "roles"}, indent=2)[:2000])
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
